name       : brewtarget
version    : 2.3.1
release    : 3
source     :
    - https://github.com/Brewtarget/brewtarget/archive/v2.3.1.tar.gz : 3314a2cff04750255b722722613ff40510f8720180b3c75e54af51a1a3a7e10e
license    : GPL-3.0
component  : desktop
summary    : A free and open-source brewing software and beer recipe creation tool
description: |
    Brewtarget is free open-source brewing software, and a beer recipe creation tool available for
    Linux, Mac, and Windows. It automatically calculates color, bitterness, and other parameters
    for you while you drag and drop ingredients into the recipe. Brewtarget also has many other
    tools such as priming sugar calculators, OG correction help, and a unique mash designing tool.
    It also can export and import recipes in BeerXML, allowing you to easily share recipes with
    friends who use BeerSmith or other programs. All of this means that Brewtarget is your single,
    free, go-to tool when crafting your beer recipes.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(gl)
rundeps    :
    - qt5-svg
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
