name       : brewtarget
version    : 3.0.1
release    : 5
source     :
    - https://github.com/Brewtarget/brewtarget/archive/refs/tags/v3.0.1.tar.gz : 9b8588152184fc4a242af8df204dd103513e720183accad788a7c0610e5132b9
homepage   : https://github.com/Brewtarget/brewtarget
license    : GPL-3.0-or-later
component  : desktop
summary    : A free and open-source brewing software and beer recipe creation tool
description: |
    Brewtarget is free open-source brewing software, and a beer recipe creation tool available for Linux, Mac, and Windows. It automatically calculates color, bitterness, and other parameters for you while you drag and drop ingredients into the recipe. Brewtarget also has many other tools such as priming sugar calculators, OG correction help, and a unique mash designing tool. It also can export and import recipes in BeerXML, allowing you to easily share recipes with friends who use BeerSmith or other programs. All of this means that Brewtarget is your single, free, go-to tool when crafting your beer recipes.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gl)
    - pkgconfig(xalan-c)
    - pkgconfig(xerces-c)
    - libboost-devel
rundeps    :
    - qt5-svg
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-icon-and-desktop-file-installation.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
